package com.chowis.country_picker_dialog

import com.chowis.country_picker_dialog.model.Country

object CountryPickerUtils {
    fun prepareCountryList():List<Country>{
        val countries = mutableListOf<Country>()
        countries.add(Country(id=1,name="Andorra",phoneCode="376",countryCode="AD"))
        countries.add(Country(id=2,name="United Arab Emirates",phoneCode="971",countryCode="AE"))
        countries.add(Country(id=3,name="Afghanistan",phoneCode="93",countryCode="AF"))
        countries.add(Country(id=4,name="Antigua and Barbuda",phoneCode="1-268",countryCode="AG"))
        countries.add(Country(id=5,name="Anguilla",phoneCode="1-264",countryCode="AI"))
        countries.add(Country(id=6,name="Albania",phoneCode="355",countryCode="AL"))
        countries.add(Country(id=7,name="Armenia",phoneCode="374",countryCode="AM"))
        countries.add(Country(id=8,name="Angola",phoneCode="244",countryCode="AO"))
        countries.add(Country(id=9,name="Antarctica",phoneCode="672",countryCode="AQ"))
        countries.add(Country(id=10,name="Argentina",phoneCode="54",countryCode="AR"))
        countries.add(Country(id=11,name="American Samoa",phoneCode="1-684",countryCode="AS"))
        countries.add(Country(id=12,name="Austria",phoneCode="43",countryCode="AT"))
        countries.add(Country(id=13,name="Australia",phoneCode="61",countryCode="AU"))
        countries.add(Country(id=14,name="Aruba",phoneCode="297",countryCode="AW"))
        countries.add(Country(id=15,name="Åland Islands",phoneCode="358",countryCode="AX"))
        countries.add(Country(id=16,name="Azerbaijan",phoneCode="994",countryCode="AZ"))
        countries.add(Country(id=17,name="Bosnia and Herzegovina",phoneCode="387",countryCode="BA"))
        countries.add(Country(id=18,name="Barbados",phoneCode="1-246",countryCode="BB"))
        countries.add(Country(id=19,name="Bangladesh",phoneCode="880",countryCode="BD"))
        countries.add(Country(id=20,name="Belgium",phoneCode="32",countryCode="BE"))
        countries.add(Country(id=21,name="Burkina Faso",phoneCode="226",countryCode="BF"))
        countries.add(Country(id=22,name="Bulgaria",phoneCode="359",countryCode="BG"))
        countries.add(Country(id=23,name="Bahrain",phoneCode="973",countryCode="BH"))
        countries.add(Country(id=24,name="Burundi",phoneCode="257",countryCode="BI"))
        countries.add(Country(id=25,name="Benin",phoneCode="229",countryCode="BJ"))
        countries.add(Country(id=26,name="Saint Barthélemy",phoneCode="590",countryCode="BL"))
        countries.add(Country(id=27,name="Bermuda",phoneCode="1-441",countryCode="BM"))
        countries.add(Country(id=28,name="Brunei Darussalam",phoneCode="673",countryCode="BN"))
        countries.add(Country(id=29,name="Bolivia (Plurinational State of)",phoneCode="591",countryCode="BO"))
        countries.add(Country(id=30,name="Bonaire, Sint Eustatius and Saba",phoneCode="599",countryCode="BQ"))
        countries.add(Country(id=31,name="Brazil",phoneCode="55",countryCode="BR"))
        countries.add(Country(id=32,name="Bahamas",phoneCode="1-242",countryCode="BS"))
        countries.add(Country(id=33,name="Bhutan",phoneCode="975",countryCode="BT"))
        countries.add(Country(id=34,name="Bouvet Island",phoneCode="47",countryCode="BV"))
        countries.add(Country(id=35,name="Botswana",phoneCode="267",countryCode="BW"))
        countries.add(Country(id=36,name="Belarus",phoneCode="375",countryCode="BY"))
        countries.add(Country(id=37,name="Belize",phoneCode="501",countryCode="BZ"))
        countries.add(Country(id=38,name="Canada",phoneCode="1",countryCode="CA"))
        countries.add(Country(id=39,name="Cocos (Keeling) Islands",phoneCode="61",countryCode="CC"))
        countries.add(Country(id=40,name="Congo, Democratic Republic of the",phoneCode="243",countryCode="CD"))
        countries.add(Country(id=41,name="Central African Republic",phoneCode="236",countryCode="CF"))
        countries.add(Country(id=42,name="Congo",phoneCode="242",countryCode="CG"))
        countries.add(Country(id=43,name="Switzerland",phoneCode="41",countryCode="CH"))
        countries.add(Country(id=44,name="Côte d'Ivoire",phoneCode="225",countryCode="CI"))
        countries.add(Country(id=45,name="Cook Islands",phoneCode="682",countryCode="CK"))
        countries.add(Country(id=46,name="Chile",phoneCode="56",countryCode="CL"))
        countries.add(Country(id=47,name="Cameroon",phoneCode="237",countryCode="CM"))
        countries.add(Country(id=48,name="China",phoneCode="86",countryCode="CN"))
        countries.add(Country(id=49,name="Colombia",phoneCode="57",countryCode="CO"))
        countries.add(Country(id=50,name="Costa Rica",phoneCode="506",countryCode="CR"))
        countries.add(Country(id=51,name="Cuba",phoneCode="53",countryCode="CU"))
        countries.add(Country(id=52,name="Cabo Verde",phoneCode="238",countryCode="CV"))
        countries.add(Country(id=53,name="Curaçao",phoneCode="599",countryCode="CW"))
        countries.add(Country(id=54,name="Christmas Island",phoneCode="61",countryCode="CX"))
        countries.add(Country(id=55,name="Cyprus",phoneCode="357",countryCode="CY"))
        countries.add(Country(id=56,name="Czechia",phoneCode="420",countryCode="CZ"))
        countries.add(Country(id=57,name="Germany",phoneCode="49",countryCode="DE"))
        countries.add(Country(id=58,name="Djibouti",phoneCode="253",countryCode="DJ"))
        countries.add(Country(id=59,name="Denmark",phoneCode="45",countryCode="DK"))
        countries.add(Country(id=60,name="Dominica",phoneCode="1-767",countryCode="DM"))
        countries.add(Country(id=61,name="Dominican Republic",phoneCode="1-849",countryCode="DO"))
        countries.add(Country(id=62,name="Algeria",phoneCode="213",countryCode="DZ"))
        countries.add(Country(id=63,name="Ecuador",phoneCode="593",countryCode="EC"))
        countries.add(Country(id=64,name="Estonia",phoneCode="372",countryCode="EE"))
        countries.add(Country(id=65,name="Egypt",phoneCode="20",countryCode="EG"))
        countries.add(Country(id=66,name="Western Sahara",phoneCode="212",countryCode="EH"))
        countries.add(Country(id=67,name="Eritrea",phoneCode="291",countryCode="ER"))
        countries.add(Country(id=68,name="Spain",phoneCode="34",countryCode="ES"))
        countries.add(Country(id=69,name="Ethiopia",phoneCode="251",countryCode="ET"))
        countries.add(Country(id=70,name="Finland",phoneCode="358",countryCode="FI"))
        countries.add(Country(id=71,name="Fiji",phoneCode="679",countryCode="FJ"))
        countries.add(Country(id=72,name="Falkland Islands (Malvinas)",phoneCode="500",countryCode="FK"))
        countries.add(Country(id=73,name="Micronesia (Federated States of)",phoneCode="691",countryCode="FM"))
        countries.add(Country(id=74,name="Faroe Islands",phoneCode="298",countryCode="FO"))
        countries.add(Country(id=75,name="France",phoneCode="33",countryCode="FR"))
        countries.add(Country(id=76,name="Gabon",phoneCode="241",countryCode="GA"))
        countries.add(Country(id=77,name="United Kingdom of Great Britain and Northern Ireland",phoneCode="44",countryCode="GB"))
        countries.add(Country(id=78,name="Grenada",phoneCode="1-473",countryCode="GD"))
        countries.add(Country(id=79,name="Georgia",phoneCode="995",countryCode="GE"))
        countries.add(Country(id=80,name="French Guiana",phoneCode="594",countryCode="GF"))
        countries.add(Country(id=81,name="Ghana",phoneCode="233",countryCode="GH"))
        countries.add(Country(id=82,name="Gibraltar",phoneCode="350",countryCode="GI"))
        countries.add(Country(id=83,name="Greenland",phoneCode="299",countryCode="GL"))
        countries.add(Country(id=84,name="Gambia",phoneCode="220",countryCode="GM"))
        countries.add(Country(id=85,name="Guinea",phoneCode="224",countryCode="GN"))
        countries.add(Country(id=86,name="Guadeloupe",phoneCode="590",countryCode="GP"))
        countries.add(Country(id=87,name="Equatorial Guinea",phoneCode="240",countryCode="GQ"))
        countries.add(Country(id=88,name="Greece",phoneCode="30",countryCode="GR"))
        countries.add(Country(id=89,name="South Georgia and the South Sandwich Islands",phoneCode="500",countryCode="GS"))
        countries.add(Country(id=90,name="Guatemala",phoneCode="502",countryCode="GT"))
        countries.add(Country(id=91,name="Guam",phoneCode="1-671",countryCode="GU"))
        countries.add(Country(id=92,name="Guinea-Bissau",phoneCode="245",countryCode="GW"))
        countries.add(Country(id=93,name="Guyana",phoneCode="592",countryCode="GY"))
        countries.add(Country(id=94,name="Hong Kong",phoneCode="852",countryCode="HK"))
        countries.add(Country(id=95,name="Heard Island and McDonald Islands",phoneCode="61",countryCode="HM"))
        countries.add(Country(id=96,name="Honduras",phoneCode="504",countryCode="HN"))
        countries.add(Country(id=97,name="Croatia",phoneCode="385",countryCode="HR"))
        countries.add(Country(id=98,name="Haiti",phoneCode="509",countryCode="HT"))
        countries.add(Country(id=99,name="Hungary",phoneCode="36",countryCode="HU"))
        countries.add(Country(id=100,name="Indonesia",phoneCode="62",countryCode="ID"))
        countries.add(Country(id=101,name="Ireland",phoneCode="353",countryCode="IE"))
        countries.add(Country(id=102,name="Israel",phoneCode="972",countryCode="IL"))
        countries.add(Country(id=103,name="India",phoneCode="91",countryCode="IN"))
        countries.add(Country(id=104,name="British Indian Ocean Territory",phoneCode="246",countryCode="IO"))
        countries.add(Country(id=105,name="Iraq",phoneCode="964",countryCode="IQ"))
        countries.add(Country(id=106,name="Iran (Islamic Republic of)",phoneCode="98",countryCode="IR"))
        countries.add(Country(id=107,name="Iceland",phoneCode="354",countryCode="IS"))
        countries.add(Country(id=108,name="Italy",phoneCode="39",countryCode="IT"))
        countries.add(Country(id=109,name="Jamaica",phoneCode="1-876",countryCode="JM"))
        countries.add(Country(id=110,name="Jordan",phoneCode="962",countryCode="JO"))
        countries.add(Country(id=111,name="Japan",phoneCode="81",countryCode="JP"))
        countries.add(Country(id=112,name="Kenya",phoneCode="254",countryCode="KE"))
        countries.add(Country(id=113,name="Kyrgyzstan",phoneCode="996",countryCode="KG"))
        countries.add(Country(id=114,name="Cambodia",phoneCode="855",countryCode="KH"))
        countries.add(Country(id=115,name="Kiribati",phoneCode="686",countryCode="KI"))
        countries.add(Country(id=116,name="Comoros",phoneCode="269",countryCode="KM"))
        countries.add(Country(id=117,name="Saint Kitts and Nevis",phoneCode="1-869",countryCode="KN"))
        countries.add(Country(id=118,name="Korea (Democratic People's Republic of)",phoneCode="850",countryCode="KP"))
        countries.add(Country(id=119,name="Korea, Republic of",phoneCode="82",countryCode="KR"))
        countries.add(Country(id=120,name="Kuwait",phoneCode="965",countryCode="KW"))
        countries.add(Country(id=121,name="Cayman Islands",phoneCode="1-345",countryCode="KY"))
        countries.add(Country(id=122,name="Kazakhstan",phoneCode="7",countryCode="KZ"))
        countries.add(Country(id=123,name="Lao People's Democratic Republic",phoneCode="856",countryCode="LA"))
        countries.add(Country(id=124,name="Lebanon",phoneCode="961",countryCode="LB"))
        countries.add(Country(id=125,name="Saint Lucia",phoneCode="1-758",countryCode="LC"))
        countries.add(Country(id=126,name="Liechtenstein",phoneCode="423",countryCode="LI"))
        countries.add(Country(id=127,name="Sri Lanka",phoneCode="94",countryCode="LK"))
        countries.add(Country(id=128,name="Liberia",phoneCode="231",countryCode="LR"))
        countries.add(Country(id=129,name="Lesotho",phoneCode="266",countryCode="LS"))
        countries.add(Country(id=130,name="Lithuania",phoneCode="370",countryCode="LT"))
        countries.add(Country(id=131,name="Luxembourg",phoneCode="352",countryCode="LU"))
        countries.add(Country(id=132,name="Latvia",phoneCode="371",countryCode="LV"))
        countries.add(Country(id=133,name="Libya",phoneCode="218",countryCode="LY"))
        countries.add(Country(id=134,name="Morocco",phoneCode="212",countryCode="MA"))
        countries.add(Country(id=135,name="Monaco",phoneCode="377",countryCode="MC"))
        countries.add(Country(id=136,name="Moldova, Republic of",phoneCode="373",countryCode="MD"))
        countries.add(Country(id=137,name="Montenegro",phoneCode="382",countryCode="ME"))
        countries.add(Country(id=138,name="Saint Martin (French part)",phoneCode="590",countryCode="MF"))
        countries.add(Country(id=139,name="Madagascar",phoneCode="261",countryCode="MG"))
        countries.add(Country(id=140,name="Marshall Islands",phoneCode="692",countryCode="MH"))
        countries.add(Country(id=141,name="North Macedonia",phoneCode="389",countryCode="MK"))
        countries.add(Country(id=142,name="Mali",phoneCode="223",countryCode="ML"))
        countries.add(Country(id=143,name="Myanmar",phoneCode="95",countryCode="MM"))
        countries.add(Country(id=144,name="Mongolia",phoneCode="976",countryCode="MN"))
        countries.add(Country(id=145,name="Macao",phoneCode="853",countryCode="MO"))
        countries.add(Country(id=146,name="Northern Mariana Islands",phoneCode="1-670",countryCode="MP"))
        countries.add(Country(id=147,name="Martinique",phoneCode="596",countryCode="MQ"))
        countries.add(Country(id=148,name="Mauritania",phoneCode="222",countryCode="MR"))
        countries.add(Country(id=149,name="Montserrat",phoneCode="1-664",countryCode="MS"))
        countries.add(Country(id=150,name="Malta",phoneCode="356",countryCode="MT"))
        countries.add(Country(id=151,name="Mauritius",phoneCode="230",countryCode="MU"))
        countries.add(Country(id=152,name="Maldives",phoneCode="960",countryCode="MV"))
        countries.add(Country(id=153,name="Malawi",phoneCode="265",countryCode="MW"))
        countries.add(Country(id=154,name="Mexico",phoneCode="52",countryCode="MX"))
        countries.add(Country(id=155,name="Malaysia",phoneCode="60",countryCode="MY"))
        countries.add(Country(id=156,name="Mozambique",phoneCode="258",countryCode="MZ"))
        countries.add(Country(id=157,name="New Caledonia",phoneCode="687",countryCode="NC"))
        countries.add(Country(id=158,name="Niger",phoneCode="227",countryCode="NE"))
        countries.add(Country(id=159,name="Norfolk Island",phoneCode="672",countryCode="NF"))
        countries.add(Country(id=160,name="Nigeria",phoneCode="234",countryCode="NG"))
        countries.add(Country(id=161,name="Nicaragua",phoneCode="505",countryCode="NI"))
        countries.add(Country(id=162,name="Netherlands",phoneCode="31",countryCode="NL"))
        countries.add(Country(id=163,name="Norway",phoneCode="47",countryCode="NO"))
        countries.add(Country(id=164,name="Nepal",phoneCode="977",countryCode="NP"))
        countries.add(Country(id=165,name="Nauru",phoneCode="674",countryCode="NR"))
        countries.add(Country(id=166,name="Niue",phoneCode="683",countryCode="NU"))
        countries.add(Country(id=167,name="New Zealand",phoneCode="64",countryCode="NZ"))
        countries.add(Country(id=168,name="Oman",phoneCode="968",countryCode="OM"))
        countries.add(Country(id=169,name="Panama",phoneCode="507",countryCode="PA"))
        countries.add(Country(id=170,name="Peru",phoneCode="51",countryCode="PE"))
        countries.add(Country(id=171,name="French Polynesia",phoneCode="689",countryCode="PF"))
        countries.add(Country(id=172,name="Papua New Guinea",phoneCode="675",countryCode="PG"))
        countries.add(Country(id=173,name="Philippines",phoneCode="63",countryCode="PH"))
        countries.add(Country(id=174,name="Pakistan",phoneCode="92",countryCode="PK"))
        countries.add(Country(id=175,name="Poland",phoneCode="48",countryCode="PL"))
        countries.add(Country(id=176,name="Saint Pierre and Miquelon",phoneCode="508",countryCode="PM"))
        countries.add(Country(id=177,name="Pitcairn",phoneCode="64",countryCode="PN"))
        countries.add(Country(id=178,name="Puerto Rico",phoneCode="1-939",countryCode="PR"))
        countries.add(Country(id=179,name="Palestine, State of",phoneCode="970",countryCode="PS"))
        countries.add(Country(id=180,name="Portugal",phoneCode="351",countryCode="PT"))
        countries.add(Country(id=181,name="Palau",phoneCode="680",countryCode="PW"))
        countries.add(Country(id=182,name="Paraguay",phoneCode="595",countryCode="PY"))
        countries.add(Country(id=183,name="Qatar",phoneCode="974",countryCode="QA"))
        countries.add(Country(id=184,name="Réunion",phoneCode="262",countryCode="RE"))
        countries.add(Country(id=185,name="Romania",phoneCode="40",countryCode="RO"))
        countries.add(Country(id=186,name="Serbia",phoneCode="381",countryCode="RS"))
        countries.add(Country(id=187,name="Russian Federation",phoneCode="7",countryCode="RU"))
        countries.add(Country(id=188,name="Rwanda",phoneCode="250",countryCode="RW"))
        countries.add(Country(id=189,name="Saudi Arabia",phoneCode="966",countryCode="SA"))
        countries.add(Country(id=190,name="Solomon Islands",phoneCode="677",countryCode="SB"))
        countries.add(Country(id=191,name="Seychelles",phoneCode="248",countryCode="SC"))
        countries.add(Country(id=192,name="Sudan",phoneCode="249",countryCode="SD"))
        countries.add(Country(id=193,name="Sweden",phoneCode="46",countryCode="SE"))
        countries.add(Country(id=194,name="Singapore",phoneCode="65",countryCode="SG"))
        countries.add(Country(id=195,name="Saint Helena, Ascension and Tristan da Cunha",phoneCode="290",countryCode="SH"))
        countries.add(Country(id=196,name="Slovenia",phoneCode="386",countryCode="SI"))
        countries.add(Country(id=197,name="Svalbard and Jan Mayen",phoneCode="47",countryCode="SJ"))
        countries.add(Country(id=198,name="Slovakia",phoneCode="421",countryCode="SK"))
        countries.add(Country(id=199,name="Sierra Leone",phoneCode="232",countryCode="SL"))
        countries.add(Country(id=200,name="San Marino",phoneCode="378",countryCode="SM"))
        countries.add(Country(id=201,name="Senegal",phoneCode="221",countryCode="SN"))
        countries.add(Country(id=202,name="Somalia",phoneCode="252",countryCode="SO"))
        countries.add(Country(id=203,name="Suriname",phoneCode="597",countryCode="SR"))
        countries.add(Country(id=204,name="South Sudan",phoneCode="211",countryCode="SS"))
        countries.add(Country(id=205,name="Sao Tome and Principe",phoneCode="239",countryCode="ST"))
        countries.add(Country(id=206,name="El Salvador",phoneCode="503",countryCode="SV"))
        countries.add(Country(id=207,name="Sint Maarten (Dutch part)",phoneCode="1-721",countryCode="SX"))
        countries.add(Country(id=208,name="Syrian Arab Republic",phoneCode="963",countryCode="SY"))
        countries.add(Country(id=209,name="Eswatini",phoneCode="268",countryCode="SZ"))
        countries.add(Country(id=210,name="Turks and Caicos Islands",phoneCode="1-649",countryCode="TC"))
        countries.add(Country(id=211,name="Chad",phoneCode="235",countryCode="TD"))
        countries.add(Country(id=212,name="French Southern Territories",phoneCode="262",countryCode="TF"))
        countries.add(Country(id=213,name="Togo",phoneCode="228",countryCode="TG"))
        countries.add(Country(id=214,name="Thailand",phoneCode="66",countryCode="TH"))
        countries.add(Country(id=215,name="Tajikistan",phoneCode="992",countryCode="TJ"))
        countries.add(Country(id=216,name="Tokelau",phoneCode="690",countryCode="TK"))
        countries.add(Country(id=217,name="Timor-Leste",phoneCode="670",countryCode="TL"))
        countries.add(Country(id=218,name="Turkmenistan",phoneCode="993",countryCode="TM"))
        countries.add(Country(id=219,name="Tunisia",phoneCode="216",countryCode="TN"))
        countries.add(Country(id=220,name="Tonga",phoneCode="676",countryCode="TO"))
        countries.add(Country(id=221,name="Türkiye",phoneCode="90",countryCode="TR"))
        countries.add(Country(id=222,name="Trinidad and Tobago",phoneCode="1-868",countryCode="TT"))
        countries.add(Country(id=223,name="Tuvalu",phoneCode="688",countryCode="TV"))
        countries.add(Country(id=224,name="Taiwan, Province of China",phoneCode="886",countryCode="TW"))
        countries.add(Country(id=225,name="Tanzania, United Republic of",phoneCode="255",countryCode="TZ"))
        countries.add(Country(id=226,name="Ukraine",phoneCode="380",countryCode="UA"))
        countries.add(Country(id=227,name="Uganda",phoneCode="256",countryCode="UG"))
        countries.add(Country(id=228,name="United States Minor Outlying Islands",phoneCode="1",countryCode="UM"))
        countries.add(Country(id=229,name="United States of America",phoneCode="1",countryCode="US"))
        countries.add(Country(id=230,name="Uruguay",phoneCode="598",countryCode="UY"))
        countries.add(Country(id=231,name="Uzbekistan",phoneCode="998",countryCode="UZ"))
        countries.add(Country(id=232,name="Holy See",phoneCode="379",countryCode="VA"))
        countries.add(Country(id=233,name="Saint Vincent and the Grenadines",phoneCode="1-784",countryCode="VC"))
        countries.add(Country(id=234,name="Venezuela (Bolivarian Republic of)",phoneCode="58",countryCode="VE"))
        countries.add(Country(id=235,name="Virgin Islands (British)",phoneCode="1-284",countryCode="VG"))
        countries.add(Country(id=236,name="Virgin Islands (U.S.)",phoneCode="1-340",countryCode="VI"))
        countries.add(Country(id=237,name="Viet Nam",phoneCode="84",countryCode="VN"))
        countries.add(Country(id=238,name="Vanuatu",phoneCode="678",countryCode="VU"))
        countries.add(Country(id=239,name="Wallis and Futuna",phoneCode="681",countryCode="WF"))
        countries.add(Country(id=240,name="Samoa",phoneCode="685",countryCode="WS"))
        countries.add(Country(id=241,name="Yemen",phoneCode="967",countryCode="YE"))
        countries.add(Country(id=242,name="Mayotte",phoneCode="262",countryCode="YT"))
        countries.add(Country(id=243,name="South Africa",phoneCode="27",countryCode="ZA"))
        countries.add(Country(id=244,name="Zambia",phoneCode="260",countryCode="ZM"))
        countries.add(Country(id=245,name="Zimbabwe",phoneCode="263",countryCode="ZW"))
        countries.add(Country(id=246,name="Guernsey",phoneCode="44-1481",countryCode="GG"))
        countries.add(Country(id=247,name="Isle of Man",phoneCode="44-1624",countryCode="IM"))
        countries.add(Country(id=248,name="Jersey",phoneCode="44-1534",countryCode="JE"))


        return countries.sortedBy { it.name }
    }
}